In [1]:
import numpy as np 
import pandas as pd

type(np)

module

In [7]:
import pandas as pd

arr = np.array([[1,2,3,],
              [4,5,6]])
res=pd.Series(arr)
res

ValueError: ignored

In [14]:
import numpy as np 
import pandas as pd

a = np.array([1,2,3,44,5,5,6,6,77,8,9,0])
ab = pd.Series(a)
print(ab)
type(a)
print(ab.shape)

0      1
1      2
2      3
3     44
4      5
5      5
6      6
7      6
8     77
9      8
10     9
11     0
dtype: int64
(12,)


In [62]:
from numpy.core.multiarray import concatenate
import pandas as pd
import numpy as np

new = np.array([1,2,3,4,5,6,7,8,9])
old = np.array([10,11,12,13,14,15,16,17,18])
#c = concatenate((new,old),axis = 0)
#c = np.dstack((new,old))
print(np.sort(old))
print(np.zeros((4,4)))
print(np.ones((4,4)))


[10 11 12 13 14 15 16 17 18]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


TypeError: ignored

In [71]:
a = np.array([[1,2,3,4,4],[5,6,7,9,10]])
res = np.sum(a)
res


b = np.random.randn(10,100,(2,5))
b



TypeError: ignored