In [4]:
import numpy as np 


num = np.array([[1,2,3],[9,9,7],[8,9,0]])
type(num)

numpy.ndarray

In [19]:
print(num[0:2,0:2])

[[1 2]
 [9 9]]


In [40]:
num2 = [1,2,3,4,4,5,6,6,7,8,9,10]
b = np.array( num2)
print(b)

[ 1  2  3  4  4  5  6  6  7  8  9 10]


In [41]:
c = b.reshape(2,3,2)
c

array([[[ 1,  2],
        [ 3,  4],
        [ 4,  5]],

       [[ 6,  6],
        [ 7,  8],
        [ 9, 10]]])

In [44]:
z = c.reshape(-1)
z

array([ 1,  2,  3,  4,  4,  5,  6,  6,  7,  8,  9, 10])

In [45]:
for i in z:
  print(i)

1
2
3
4
4
5
6
6
7
8
9
10


In [51]:
y = np.array([[1,2,3,4],[5,6,7,8]])
for a in y:
  for b in a:
    print(b)

1
2
3
4
5
6
7
8


In [54]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9,10])
z = np.concatenate((a,b),axis = 0)
z


array([ 1,  2,  3,  4,  5,  5,  6,  7,  8,  9, 10])

In [60]:
c = z.copy()
c.view()
c


array([ 1,  2,  3,  4,  5,  5,  6,  7,  8, 76, 10])

In [62]:
x = np.zeros((3,3), dtype = "i")
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [64]:
x = np.ones((4,4), dtype = "f")
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [66]:
x = np.full((4,4),3)
x

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [73]:
a = np.array([[4,6,7,8,9,10],[5,5,7,8,9,10]])
print(a)


[[ 4  6  7  8  9 10]
 [ 5  5  7  8  9 10]]


In [78]:
print(np.mean(a,axis= 0))
print(np.mean(a,axis= 1))

[ 4.5  5.5  7.   8.   9.  10. ]
[7.33333333 7.33333333]


In [81]:
x = np.random.randint(10,100,(4,4))
x 

array([[94, 20, 83, 93],
       [72, 69, 98, 82],
       [48, 33, 63, 37],
       [34, 67, 94, 41]])

In [84]:
x = np.linspace(10,100,8)
x

array([ 10.        ,  22.85714286,  35.71428571,  48.57142857,
        61.42857143,  74.28571429,  87.14285714, 100.        ])